[build]
  image = "formbricks/formbricks:latest"

[env]
  NEXTAUTH_SECRET = "AGO7JKC0Fq/wULaUfos3HbGGN2hsieWv07IWuLUfNSk="
  NEXTAUTH_URL = "https://form-omd.fly.dev"
  DATABASE_URL = "postgresql://postgres:m0johAUjLRKymwx@n8n-omd-bd.flycast:5432/formbricks"
  FORMBRICKS_ENVIRONMENT = "cloud"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200
